name: Sync Docker Images

on: 
  push:
    branches:
      - main

jobs:
  sync-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Login to Alibaba Cloud Registry
        env:
          ALIBABA_CLOUD_REGISTRY: registry.cn-beijing.aliyuncs.com
          USERNAME: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          PASSWORD: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        run: |
          echo $PASSWORD | docker login $ALIBABA_CLOUD_REGISTRY -u $USERNAME --password-stdin

      - name: Use Skopeo Tools to Sync Images to Alibaba Cloud
        run: |
          skopeo copy docker://docker.io/library/mysql:8.0.33 docker://registry.cn-beijing.aliyuncs.com/godwin/mysql:8.0.33
          skopeo copy docker://docker.io/library/redis:7.0.12 docker://registry.cn-beijing.aliyuncs.com/godwin/redis:7.0.12
          skopeo copy docker://docker.io/library/nginx:latest docker://registry.cn-beijing.aliyuncs.com/godwin/nginx:latest
          skopeo copy docker://docker.io/library/elasticsearch:7.6.1 docker://registry.cn-beijing.aliyuncs.com/godwin/elasticsearch:7.6.1
          skopeo copy docker://docker.io/library/elasticsearch:latest docker://registry.cn-beijing.aliyuncs.com/godwin/elasticsearch:latest
          skopeo copy docker://docker.io/library/zookeeper:3.9.2 docker://registry.cn-beijing.aliyuncs.com/godwin/zookeeper:3.9.2
